modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/HaloOfBlocks/ProjectArsenal/issues"

[[mods]]
modId="projectarsenal"
version="0.2.1"
displayName="Project Arsenal"
updateJSONURL="https://raw.githubusercontent.com/HaloOfBlocks/VersionChecker/main/projectarsenal/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/project-arsenal"
logoFile="icon.png"
credits="The community of Project Arsenal"
authors="Halo of Blocks Team: Autovw, CasualNoLifer"
description='''
A community project and add-on to MrCrayfish's Gun Mod
'''

[[dependencies.projectarsenal]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectarsenal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectarsenal]]
    modId="cgm"
    mandatory=true
    versionRange="[1.2.7,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectarsenal]]
    modId="framework"
    mandatory=true
    versionRange="[0.2.4,)"
    ordering="NONE"
    side="BOTH"

[modproperties.projectarsenal]
    catalogueImageIcon="icon.png"
    configuredBackground="minecraft:textures/block/anvil.png"
